In [ ]:
# importando a biblioteca numpy e importando numpy para np
import numpy

In [ ]:
import numpy as np

In [ ]:
# criando um array 2d (possui linhas e colunas, como uma matriz)
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                  [65.4, 59.2, 63.6, 88.4, 68.7],
                  [22.3, 42.7, 11.8, 90.5, 36.3]])
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ],
       [22.3 , 42.7 , 11.8 , 90.5 , 36.3 ]])

In [ ]:
# exibindo a estrutura de np_2d
np_2d.shape

(3, 5)

In [ ]:
# modificando um elemento int para str e assim alterando todos os outros
np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
          [65.4, 59.2, 63.6, 88.4, '68.7' ]])

array([['1.73', '1.68', '1.71', '1.89', '1.79'],
       ['65.4', '59.2', '63.6', '88.4', '68.7']], dtype='<U32')

In [ ]:
# criando outro array matriz
np = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [ ]:
# exibindo a estrutura de np
np.shape

(3, 3)

In [ ]:
# exibindo a primeira linha de np_2 
np_2d[0]

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [ ]:
# exibindo o valor da primeira linha e terceira coluna de np_2d
np_2d[0,2]

1.71

In [ ]:
np_2d[0][2]

1.71

In [ ]:
# exibindo todas as linhas, mas somente da segunda coluna até a última coluna
np_2d [:, 1:3]

array([[ 1.68,  1.71],
       [59.2 , 63.6 ],
       [42.7 , 11.8 ]])

In [ ]:
# exibindo apenas a primeira linha e todas as colunas que a pertecem  
np_2d [1, :]

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [ ]:
# crie uma lista chamada baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]
import numpy as np
# transforme a lista baseball em um array np_baseball
np_baseball = np.array(baseball)
type(np_baseball)

numpy.ndarray

In [ ]:
# exiba a estrutura de np_baseball
np_baseball.shape

(8,)

In [ ]:
# importe a biblioteca random e importe random para rd
import random
import random as rd

In [ ]:
# geração de números entre 150 e 209
height = range(150, 210)
# geração de números entre 50 e 149
weight = range(50, 150)
# amostra randomica de 20 números de height
height = rd.sample(height,20)
# amostra randomica de 20 números de weight
weight= rd.sample(weight,20)
# converter height em array e normalizar multiplicando por 0.01
height_array = np.array(height)*0.01
# converter weight em array
weight_array = np.array(weight)
# calculo do bmi
bmi = weight_array/height_array **2
# verificando onde bmi é menor que 21
light = [bmi<21]
print(light)
# exibição dos valores de bmi com valor menor que 21
bmi[bmi<21]

[array([False,  True, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False,  True, False,
       False, False])]


array([19.41568047, 17.57706869, 17.07678956])

In [ ]:
# print os elementos de weight_array do index 8 até o index 15, incluindo o 15
print(weight_array[7:15])

[114  92 131 139 122  52  76  66]


In [ ]:
# print os elementos de height_array do index 11 até o index 19, incluindo o 19
print(height_array[10:19])

[1.52 2.07 1.72 1.5  1.56 2.03 1.89 1.75 1.51]


In [ ]:
# crie uma lista de listas chamada baseball
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]
np_baseball = np.array(baseball)
print(np_baseball[2])

[210.   98.5]


In [ ]:
# crie uma nova variável np_weight_lb que recebe toda a segunda coluna de np_baseball
np_weight_lb = np_baseball[:, 1]
np_weight_lb

array([ 78.4, 102.7,  98.5,  75.2])

In [ ]:
# print a primeira coluna da segunda linha de np_baseball na linha do código
print(np_baseball[1,0])

215.0


In [ ]:
# calcule e exiba a média da primeira coluna de np_baseball
np.mean(np_baseball[:,0])

198.25

In [ ]:
# calcule e exiba a mediana da segunda linha de np_baseball
np.median(np_baseball[1,:])

158.85