In [ ]:
# exibindo todas as listas presentes no Google Colab
pip list

Package                       Version
----------------------------- --------------------
absl-py                       1.4.0
alabaster                     0.7.13
albumentations                1.2.1
altair                        4.2.2
anyio                         3.6.2
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arviz                         0.15.1
astropy                       5.2.2
astunparse                    1.6.3
attrs                         22.2.0
audioread                     3.0.0
autograd                      1.5
Babel                         2.12.1
backcall                      0.2.0
beautifulsoup4                4.11.2
bleach                        6.0.0
blis                          0.7.9
blosc2                        2.0.0
bokeh                         2.4.3
branca                        0.6.0
CacheControl                  0.12.11
cached-property               1.5.2
cachetools                    5.3.0
cata

In [ ]:
# instalando bibliotecas
pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
pip install pydicom

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 51.6 MB/s eta 0:00:00


In [ ]:
# importando a biblioteca numpy
import numpy

In [ ]:
numpy.array([1, 2, 3])

array([1, 2, 3])

In [ ]:
# importando numpy para np
import numpy as np
np.array([1, 2, 3])

array([1, 2, 3])

In [ ]:
from numpy import array
array([1, 2, 3])

array([1, 2, 3])

In [ ]:
import numpy as np
# criando a lista fam
fam = ['Rian', 18,'Paulo', 26, 'Daiane', 27, 'Socorro', 43]
# adicionando dois elementos a lista fam e criando a lista fam_ext 
fam_ext = fam + [' Alyne', 31]
# exibindo quantos elementos existem na lista fam_ext 
print(str(len(fam_ext)) + ' Elements in fam_ext')
# transformando a lista fam_ext em array
np_fam = np.array(fam_ext)

10 Elements in fam_ext


In [ ]:
# exibindo o array e a lista
print(np_fam)

['Rian' '18' 'Paulo' '26' 'Daiane' '27' 'Socorro' '43' ' Alyne' '31']


In [ ]:
print(fam_ext)

['Rian', 18, 'Paulo', 26, 'Daiane', 27, 'Socorro', 43, ' Alyne', 31]


In [ ]:
# exibindo o tipo de np_fam e fam_ext
print(type(np_fam))

<class 'numpy.ndarray'>


In [ ]:
print(type(fam_ext))

<class 'list'>


In [ ]:
# importando a biblioteca math
import math

In [ ]:
# calculando o comprimento de uma circunferencia e a area dessa circunferencia 
r = 0.43

In [ ]:
C = 2 * math.pi * r
C

2.701769682087222

In [ ]:
A = math.pi * r ** 2
A

0.5808804816487527

In [ ]:
print('Circumference: ' + str(C))

Circumference: 2.701769682087222


In [ ]:
print('Area: ' + str(A))

Area: 0.5808804816487527


In [ ]:
# tentando fazer operações com listas
height = [10, 20, 40, 80, 160]
weight = [30, 60, 120, 240, 480]
weight / height ** 2

TypeError: ignored

In [ ]:
import numpy as np
# convertendo as listas height e weight em array
np_height = np.array(height)
np_height

array([ 10,  20,  40,  80, 160])

In [ ]:
np_weight = np.array(weight)
np_weight

array([ 30,  60, 120, 240, 480])

In [ ]:
# realizando a operação tentada anteriormente
bmi = np_weight / np_height ** 2
bmi

array([0.3    , 0.15   , 0.075  , 0.0375 , 0.01875])

In [ ]:
# criando uma lista e um array para comparações
python_list = [1, 2, 3]
numpy_array = np.array([1, 2, 3])

In [ ]:
# soma de duas listas (concatenadas)
python_list + python_list

[1, 2, 3, 1, 2, 3]

In [ ]:
# soma de dois array (os elementos se somam, não se repetem)
numpy_array + numpy_array

array([2, 4, 6])

In [ ]:
# acessando valores do bmi
bmi 

array([0.3    , 0.15   , 0.075  , 0.0375 , 0.01875])

In [ ]:
bmi[1]

0.15

In [ ]:
# verificando onde bmi é menor que 0.03
bmi < 0.03

array([False, False, False, False,  True])

In [ ]:
# exibição do valor de bmi menor que 0.03
bmi[bmi < 0.03]

array([0.01875])